export type Field = { key: string; label: string; type?: "date" | "datetime-local" | "number" | "textarea" | "email" | "password" | "money" | "time" | "weekdays" | "select" | "multi" | "boolean"; options?: string[]; source?: string; optional?: boolean; capability?: string; min?: number; max?: number };
export type Spec = { title: string; singular: string; description: string; fields: Field[]; columns: string[]; statuses?: string[]; readOnly?: boolean; capability?: string; self?: boolean };
const f = (key: string, label: string, extra: Partial<Field> = {}): Field => ({ key, label, ...extra });
const employee = f("employee_id", "Nhân viên", { type: "select", source: "employees" });
const name = f("name", "Tên");
const dates = [f("starts_on", "Từ ngày", { type: "date" }), f("ends_on", "Đến ngày", { type: "date" })];
const reason = f("reason", "Lý do", { type: "textarea" });
const requestStatuses = ["DRAFT", "SUBMITTED", "APPROVED", "REJECTED", "CANCELLED"];
const roles = ["EMPLOYEE", "MANAGER", "HR_ADMIN", "SUPER_ADMIN"];
export const capabilities = ["hr:read", "hr:write", "payroll:read", "payroll:write", "documents:sensitive", "knowledge:write", "system:manage"];
export const specs: Record<string, Spec> = {
  employees: { title: "Nhân viên", singular: "nhân viên", description: "Hồ sơ, tổ chức và hành trình của mỗi thành viên.", fields: [f("code", "Mã nhân viên"), f("full_name", "Họ và tên"), f("email", "Email công việc", { type: "email" }), f("phone", "Số điện thoại", { optional: true }), f("department_id", "Phòng ban", { type: "select", source: "departments" }), f("position_id", "Chức danh", { type: "select", source: "positions" }), f("manager_id", "Quản lý trực tiếp", { type: "select", source: "employees", optional: true }), f("hire_date", "Ngày vào làm", { type: "date" }), f("status", "Trạng thái", { type: "select", options: ["ACTIVE", "ON_LEAVE"] })], columns: ["full_name", "code", "department_id", "position_id", "status", "hire_date"], statuses: ["ACTIVE", "ON_LEAVE", "ARCHIVED"] },
  departments: { title: "Phòng ban", singular: "phòng ban", description: "Cấu trúc tổ chức của Công ty ABC.", fields: [name], columns: ["name"] },
  positions: { title: "Chức danh", singular: "chức danh", description: "Các vị trí công việc trong tổ chức.", fields: [name], columns: ["name"] },
  contracts: { title: "Hợp đồng", singular: "hợp đồng", description: "Theo dõi thời hạn, điều khoản và hồ sơ đính kèm.", fields: [employee, f("title", "Tên hợp đồng"), dates[0], { ...dates[1], optional: true }, f("base_salary", "Lương cơ bản (VND)", { type: "money", capability: "payroll:write" }), f("status", "Trạng thái", { type: "select", options: ["DRAFT", "ACTIVE", "EXPIRED"] })], columns: ["title", "employee_id", "starts_on", "ends_on", "status"], statuses: ["DRAFT", "ACTIVE", "EXPIRED", "TERMINATED"] },
  shifts: { title: "Ca làm", singular: "ca làm", description: "Giờ vào, giờ ra và khoảng thời gian được phép đi muộn. Giờ ra trước giờ vào là ca qua đêm.", fields: [name, f("start_minute", "Giờ vào ca", { type: "time" }), f("end_minute", "Giờ ra ca", { type: "time" }), f("break_minutes", "Nghỉ giữa ca (phút)", { type: "number", min: 0 }), f("grace_minutes", "Cho phép trễ (phút)", { type: "number", min: 0 }), f("weekdays", "Ngày làm việc", { type: "weekdays" })], columns: ["name", "start_minute", "end_minute", "break_minutes", "grace_minutes", "weekdays"] },
  schedule: { title: "Lịch làm việc", singular: "lịch làm việc", description: "Phân ca theo nhân viên và khoảng ngày, bao gồm ca qua đêm.", fields: [employee, f("shift_id", "Ca làm", { type: "select", source: "shifts" }), ...dates], columns: ["employee_id", "shift_id", "starts_on", "ends_on"] },
  attendance: { title: "Chấm công", singular: "chấm công thủ công", description: "Theo dõi giờ vào ca, ra ca và số phút làm việc thực tế.", fields: [employee, f("action", "Thao tác", { type: "select", options: ["CHECK_IN", "CHECK_OUT"] }), f("occurred_at", "Thời điểm (giờ Việt Nam)", { type: "datetime-local" }), reason], columns: ["employee_id", "work_date", "check_in", "check_out", "worked_minutes", "late_minutes", "early_minutes", "source"] },
  corrections: { title: "Điều chỉnh công", singular: "yêu cầu điều chỉnh", description: "Mọi thay đổi đều có lý do và được phê duyệt trước khi áp dụng.", fields: [employee, f("attendance_id", "Bản ghi chấm công", { type: "select", source: "attendance" }), f("requested_in", "Giờ vào đề nghị (giờ Việt Nam)", { type: "datetime-local" }), f("requested_out", "Giờ ra đề nghị (giờ Việt Nam)", { type: "datetime-local", optional: true }), reason], columns: ["employee_id", "requested_in", "requested_out", "reason", "status"], statuses: requestStatuses, self: true },
  timesheets: { title: "Bảng công", singular: "kỳ công", description: "Rà soát trước khi khóa kỳ. Mở lại kỳ đã khóa cần ghi lý do.", fields: [name, ...dates], columns: ["name", "starts_on", "ends_on", "status"], statuses: ["DRAFT", "REVIEW", "LOCKED"] },
  leave: { title: "Nghỉ phép", singular: "đơn nghỉ phép", description: "Đăng ký nghỉ nguyên ngày, theo dõi số dư và tiến trình phê duyệt.", fields: [employee, f("type_id", "Loại nghỉ", { type: "select", source: "leave_types" }), ...dates, reason], columns: ["employee_id", "type_id", "starts_on", "ends_on", "days", "status"], statuses: requestStatuses, self: true },
  "leave-types": { title: "Loại nghỉ phép", singular: "loại nghỉ", description: "Thiết lập định mức nghỉ và loại nghỉ được trả lương.", fields: [name, f("annual_days", "Định mức năm (ngày)", { type: "number", min: 0, max: 366 }), f("paid", "Hưởng lương", { type: "boolean" })], columns: ["name", "annual_days", "paid"] },
  "leave-balances": { title: "Số dư nghỉ phép", singular: "định mức nghỉ phép", description: "Điều chỉnh định mức năm với lý do; số ngày đã dùng được tính từ các đơn đã duyệt.", fields: [employee, f("type_id", "Loại nghỉ", { type: "select", source: "leave_types" }), f("year", "Năm", { type: "number", min: 1900, max: 2200 }), f("granted", "Định mức (ngày)", { type: "number", min: 0, max: 366 }), reason], columns: ["employee_id", "type_id", "year", "granted", "used"], capability: "hr:write" },
  overtime: { title: "Tăng ca", singular: "yêu cầu tăng ca", description: "Đăng ký khung giờ làm thêm và theo dõi kết quả duyệt.", fields: [employee, f("starts_at", "Bắt đầu (giờ Việt Nam)", { type: "datetime-local" }), f("ends_at", "Kết thúc (giờ Việt Nam)", { type: "datetime-local" }), reason], columns: ["employee_id", "starts_at", "ends_at", "reason", "status"], statuses: requestStatuses, self: true },
  payroll: { title: "Bảng lương", singular: "kỳ lương", description: "Tổng hợp lương nội bộ theo bảng công và các thành phần đã cấu hình.", fields: [name, f("timesheet_id", "Kỳ công", { type: "select", source: "timesheets" })], columns: ["name", "timesheet_id", "status"], statuses: ["DRAFT", "CALCULATED", "REVIEW", "LOCKED"], capability: "payroll:write" },
  "payroll-components": { title: "Thành phần lương", singular: "thành phần lương", description: "Lương cơ bản, phụ cấp và điều chỉnh được xác nhận bởi người có quyền.", fields: [employee, name, f("amount", "Số tiền (VND)", { type: "money" }), f("kind", "Loại", { type: "select", options: ["BASE", "ALLOWANCE", "ADJUSTMENT"] }), reason], columns: ["employee_id", "name", "kind", "amount", "reason"], capability: "payroll:write" },
  performance: { title: "Đánh giá", singular: "bản đánh giá", description: "Nhận xét và điểm số do nhân viên, quản lý trực tiếp nhập.", fields: [employee, f("cycle_id", "Kỳ đánh giá", { type: "select", source: "review_cycles" }), f("self_comment", "Tự đánh giá", { type: "textarea", optional: true }), f("manager_comment", "Nhận xét quản lý", { type: "textarea", optional: true }), f("score", "Điểm (1–5)", { type: "number", min: 1, max: 5, optional: true })], columns: ["employee_id", "cycle_id", "score", "status"], statuses: ["DRAFT", "SUBMITTED", "PUBLISHED"], self: true },
  "review-cycles": { title: "Kỳ đánh giá", singular: "kỳ đánh giá", description: "Thiết lập thời gian đánh giá nhân viên.", fields: [name, ...dates], columns: ["name", "starts_on", "ends_on"] },
  announcements: { title: "Thông báo", singular: "thông báo", description: "Thông tin nội bộ dành cho đúng nhóm người nhận.", fields: [f("title", "Tiêu đề"), f("body", "Nội dung", { type: "textarea" }), f("audience", "Nhóm người nhận", { type: "multi", options: roles })], columns: ["title", "audience", "status", "created_at"], statuses: ["DRAFT", "PUBLISHED", "ARCHIVED"] },
  documents: { title: "Tài liệu", singular: "tài liệu", description: "Hồ sơ được lưu riêng tư và kiểm tra quyền ở mỗi lần tải.", fields: [f("title", "Tên tài liệu"), employee, f("classification", "Phân loại", { type: "select", options: ["GENERAL", "CONFIDENTIAL", "IDENTITY"] }), f("contract_id", "Hợp đồng liên quan", { type: "select", source: "contracts", optional: true })], columns: ["title", "employee_id", "classification", "filename", "created_at"] },
  users: { title: "Tài khoản", singular: "tài khoản", description: "Quản lý quyền truy cập và khóa tài khoản khi cần.", fields: [f("email", "Email", { type: "email" }), { ...employee, optional: true }, f("role", "Vai trò", { type: "select", options: roles }), f("capabilities", "Quyền bổ sung", { type: "multi", options: capabilities, optional: true })], columns: ["email", "employee_id", "role", "locked"], capability: "system:manage" },
  roles: { title: "Phân quyền", singular: "cấu hình vai trò", description: "Thiết lập các quyền cho từng vai trò hệ thống.", fields: [f("role", "Vai trò", { type: "select", options: roles }), f("capabilities", "Các quyền", { type: "multi", options: capabilities, optional: true })], columns: ["role", "capabilities"], capability: "system:manage" },
  settings: { title: "Thiết lập", singular: "thiết lập", description: "Tham số nghiệp vụ của hệ thống.", fields: [f("key", "Tên tham số"), f("value", "Giá trị")], columns: ["key", "value"], capability: "system:manage" },
  audit: { title: "Nhật ký hoạt động", singular: "sự kiện", description: "Dấu vết các thao tác và kết quả kiểm tra quyền.", fields: [], columns: ["created_at", "actor_id", "action", "resource_type", "result", "reason"], readOnly: true },
  notifications: { title: "Hộp thông báo", singular: "thông báo", description: "Các cập nhật và việc cần chú ý của bạn.", fields: [], columns: ["title", "created_at", "read_at"], readOnly: true },
};
export const fieldLabels: Record<string, string> = { ...Object.fromEntries(Object.values(specs).flatMap(spec => spec.fields.map(field => [field.key, field.label]))), full_name: "Nhân viên", work_date: "Ngày công", check_in: "Vào ca", check_out: "Ra ca", worked_minutes: "Làm việc (phút)", late_minutes: "Đi muộn (phút)", early_minutes: "Về sớm (phút)", source: "Nguồn", status: "Trạng thái", days: "Số ngày", created_at: "Ngày tạo", locked: "Đã khóa", filename: "Tên tệp", actor_id: "Người thực hiện", action: "Thao tác", resource_type: "Đối tượng", result: "Kết quả", read_at: "Đã đọc", base_amount: "Lương cơ bản", allowance_amount: "Phụ cấp", adjustment_amount: "Điều chỉnh", total_amount: "Tổng cộng", overtime_minutes: "Tăng ca (phút)", granted: "Được cấp", used: "Đã dùng", year: "Năm", updated_at: "Cập nhật", model_version: "Phiên bản mô hình", sample_count: "Số mẫu", review_reason: "Lý do duyệt", end_date: "Ngày nghỉ việc", recorded_days: "Ngày đã ghi công", missing_checkout: "Lượt thiếu giờ ra" };
export const capabilityLabels: Record<string, string> = { "hr:read": "Xem nhân sự toàn công ty", "hr:write": "Quản lý nhân sự", "payroll:read": "Xem lương", "payroll:write": "Quản lý lương", "documents:sensitive": "Tài liệu nhạy cảm", "knowledge:write": "Quản lý kho tri thức", "system:manage": "Quản trị hệ thống" };
